### ISSUE TITLE
bug: Gateway doesn't register on the cloud if has no internet connection when it's powered on.

### ISSUE THREAD

**Issue by alla3** [CESARBR/knot-gateway-webui#47]
Description: 
Gateway does not register on the cloud if is not connected on the internet when the gateway is powered on.
 
Steps to reproduce:
- Flash a new image
- Power the Gateway on
- Wait for a few seconds and connect it on the internet
- Try to configure the Gateway using the Web UI

Workaround:
- Connect the Gateway on the internet and reboot it

**Comment by ramonhpr** [comment]
This issue seems to be related to communication between webui and fog.

I reproduced the bug and capture the log bellow:
```[winston] Attempt to write logs with no transports {"message":"Unknown error while communicating with fog service","level":"warn"}
[winston] Attempt to write logs with no transports {"message":"IncomingMessage {\n  _readableState: \n   ReadableState {\n     objectMode: false,\n     highWaterMark: 16384,\n     buffer: BufferList { head: null, tail: null, length: 0 },\n     length: 0,\n     pipes: null,\n     pipesCount: 0,\n     flowing: true,\n     ended: true,\n     endEmitted: true,\n     reading: false,\n     sync: true,\n     needReadable: false,\n     emittedReadable: false,\n     readableListening: false,\n     resumeScheduled: false,\n     destroyed: false,\n     defaultEncoding: 'utf8',\n     awaitDrain: 0,\n     readingMore: false,\n     decoder: null,\n     encoding: null },\n  readable: false,\n  domain: null,\n  _events: \n   { end: [ [Function: responseOnEnd], [Function] ],\n     close: [ [Function], [Function] ],\n     data: [Function],\n     error: [Function] },\n  _eventsCount: 4,\n  _maxListeners: undefined,\n  socket: \n   Socket {\n     connecting: false,\n     _hadError: false,\n     _handle: null,\n     _parent: null,\n     _host: 'localhost',\n     _readableState: \n      ReadableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        buffer: [BufferList],\n        length: 0,\n        pipes: null,\n        pipesCount: 0,\n        flowing: true,\n        ended: false,\n        endEmitted: false,\n        reading: true,\n        sync: false,\n        needReadable: true,\n        emittedReadable: false,\n        readableListening: false,\n        resumeScheduled: false,\n        destroyed: true,\n        defaultEncoding: 'utf8',\n        awaitDrain: 0,\n        readingMore: false,\n        decoder: null,\n        encoding: null },\n     readable: false,\n     domain: null,\n     _events: \n      { end: [Function],\n        finish: [Function: onSocketFinish],\n        _socketEnd: [Function: onSocketEnd],\n        free: [Function: onFree],\n        close: [Array],\n        agentRemove: [Function: onRemove],\n        drain: [Function: ondrain],\n        error: [Function: socketErrorListener] },\n     _eventsCount: 8,\n     _maxListeners: undefined,\n     _writableState: \n      WritableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        finalCalled: false,\n        needDrain: false,\n        ending: true,\n        ended: true,\n        finished: true,\n        destroyed: true,\n        decodeStrings: false,\n        defaultEncoding: 'utf8',\n        length: 0,\n        writing: false,\n        corked: 0,\n        sync: false,\n        bufferProcessing: false,\n        onwrite: [Function: bound onwrite],\n        writecb: null,\n        writelen: 0,\n        bufferedRequest: null,\n        lastBufferedRequest: null,\n        pendingcb: 0,\n        prefinished: true,\n        errorEmitted: false,\n        bufferedRequestCount: 0,\n        corkedRequestsFree: [Object] },\n     writable: false,\n     allowHalfOpen: false,\n     _bytesDispatched: 236,\n     _sockname: null,\n     _pendingData: null,\n     _pendingEncoding: '',\n     server: null,\n     _server: null,\n     parser: null,\n     _httpMessage: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 5,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        upgrading: false,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedConnection: false,\n        _removedContLen: false,\n        _removedTE: false,\n        _contentLength: null,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Circular],\n        connection: [Circular],\n        _header: 'POST /devices/ HTTP/1.1\\r\\nContent-Type: application/x-www-form-urlencoded\\r\\nhost: localhost:3000\\r\\ncontent-length: 99\\r\\nConnection: close\\r\\n\\r\\n',\n        _onPendingData: [Function: noopPendingOutput],\n        agent: [Agent],\n        socketPath: undefined,\n        timeout: undefined,\n        method: 'POST',\n        path: '/devices/',\n        _ended: true,\n        res: [Circular],\n        aborted: undefined,\n        timeoutCb: null,\n        upgradeOrConnect: false,\n        parser: null,\n        maxHeadersCount: null,\n        [Symbol(outHeadersKey)]: [Object] },\n     read: [Function],\n     _consuming: true,\n     _idleNext: null,\n     _idlePrev: null,\n     _idleTimeout: -1,\n     [Symbol(asyncId)]: 1297,\n     [Symbol(bytesRead)]: 303 },\n  connection: \n   Socket {\n     connecting: false,\n     _hadError: false,\n     _handle: null,\n     _parent: null,\n     _host: 'localhost',\n     _readableState: \n      ReadableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        buffer: [BufferList],\n        length: 0,\n        pipes: null,\n        pipesCount: 0,\n        flowing: true,\n        ended: false,\n        endEmitted: false,\n        reading: true,\n        sync: false,\n        needReadable: true,\n        emittedReadable: false,\n        readableListening: false,\n        resumeScheduled: false,\n        destroyed: true,\n        defaultEncoding: 'utf8',\n        awaitDrain: 0,\n        readingMore: false,\n        decoder: null,\n        encoding: null },\n     readable: false,\n     domain: null,\n     _events: \n      { end: [Function],\n        finish: [Function: onSocketFinish],\n        _socketEnd: [Function: onSocketEnd],\n        free: [Function: onFree],\n        close: [Array],\n        agentRemove: [Function: onRemove],\n        drain: [Function: ondrain],\n        error: [Function: socketErrorListener] },\n     _eventsCount: 8,\n     _maxListeners: undefined,\n     _writableState: \n      WritableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        finalCalled: false,\n        needDrain: false,\n        ending: true,\n        ended: true,\n        finished: true,\n        destroyed: true,\n        decodeStrings: false,\n        defaultEncoding: 'utf8',\n        length: 0,\n        writing: false,\n        corked: 0,\n        sync: false,\n        bufferProcessing: false,\n        onwrite: [Function: bound onwrite],\n        writecb: null,\n        writelen: 0,\n        bufferedRequest: null,\n        lastBufferedRequest: null,\n        pendingcb: 0,\n        prefinished: true,\n        errorEmitted: false,\n        bufferedRequestCount: 0,\n        corkedRequestsFree: [Object] },\n     writable: false,\n     allowHalfOpen: false,\n     _bytesDispatched: 236,\n     _sockname: null,\n     _pendingData: null,\n     _pendingEncoding: '',\n     server: null,\n     _server: null,\n     parser: null,\n     _httpMessage: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 5,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        upgrading: false,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedConnection: false,\n        _removedContLen: false,\n        _removedTE: false,\n        _contentLength: null,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Circular],\n        connection: [Circular],\n        _header: 'POST /devices/ HTTP/1.1\\r\\nContent-Type: application/x-www-form-urlencoded\\r\\nhost: localhost:3000\\r\\ncontent-length: 99\\r\\nConnection: close\\r\\n\\r\\n',\n        _onPendingData: [Function: noopPendingOutput],\n        agent: [Agent],\n        socketPath: undefined,\n        timeout: undefined,\n        method: 'POST',\n        path: '/devices/',\n        _ended: true,\n        res: [Circular],\n        aborted: undefined,\n        timeoutCb: null,\n        upgradeOrConnect: false,\n        parser: null,\n        maxHeadersCount: null,\n        [Symbol(outHeadersKey)]: [Object] },\n     read: [Function],\n     _consuming: true,\n     _idleNext: null,\n     _idlePrev: null,\n     _idleTimeout: -1,\n     [Symbol(asyncId)]: 1297,\n     [Symbol(bytesRead)]: 303 },\n  httpVersionMajor: 1,\n  httpVersionMinor: 1,\n  httpVersion: '1.1',\n  complete: true,\n  headers: \n   { 'x-powered-by': 'Express',\n     vary: 'Origin',\n     'access-control-allow-credentials': 'true',\n     'content-type': 'application/json; charset=utf-8',\n     'content-length': '23',\n     etag: 'W/\"17-T/rW1BQtPtOdPdiL8RI/XtHXZdY\"',\n     date: 'Sun, 01 Sep 2019 17:23:31 GMT',\n     connection: 'close' },\n  rawHeaders: \n   [ 'X-Powered-By',\n     'Express',\n     'Vary',\n     'Origin',\n     'Access-Control-Allow-Credentials',\n     'true',\n     'Content-Type',\n     'application/json; charset=utf-8',\n     'Content-Length',\n     '23',\n     'ETag',\n     'W/\"17-T/rW1BQtPtOdPdiL8RI/XtHXZdY\"',\n     'Date',\n     'Sun, 01 Sep 2019 17:23:31 GMT',\n     'Connection',\n     'close' ],\n  trailers: {},\n  rawTrailers: [],\n  upgrade: false,\n  url: '',\n  method: null,\n  statusCode: 500,\n  statusMessage: 'Internal Server Error',\n  client: \n   Socket {\n     connecting: false,\n     _hadError: false,\n     _handle: null,\n     _parent: null,\n     _host: 'localhost',\n     _readableState: \n      ReadableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        buffer: [BufferList],\n        length: 0,\n        pipes: null,\n        pipesCount: 0,\n        flowing: true,\n        ended: false,\n        endEmitted: false,\n        reading: true,\n        sync: false,\n        needReadable: true,\n        emittedReadable: false,\n        readableListening: false,\n        resumeScheduled: false,\n        destroyed: true,\n        defaultEncoding: 'utf8',\n        awaitDrain: 0,\n        readingMore: false,\n        decoder: null,\n        encoding: null },\n     readable: false,\n     domain: null,\n     _events: \n      { end: [Function],\n        finish: [Function: onSocketFinish],\n        _socketEnd: [Function: onSocketEnd],\n        free: [Function: onFree],\n        close: [Array],\n        agentRemove: [Function: onRemove],\n        drain: [Function: ondrain],\n        error: [Function: socketErrorListener] },\n     _eventsCount: 8,\n     _maxListeners: undefined,\n     _writableState: \n      WritableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        finalCalled: false,\n        needDrain: false,\n        ending: true,\n        ended: true,\n        finished: true,\n        destroyed: true,\n        decodeStrings: false,\n        defaultEncoding: 'utf8',\n        length: 0,\n        writing: false,\n        corked: 0,\n        sync: false,\n        bufferProcessing: false,\n        onwrite: [Function: bound onwrite],\n        writecb: null,\n        writelen: 0,\n        bufferedRequest: null,\n        lastBufferedRequest: null,\n        pendingcb: 0,\n        prefinished: true,\n        errorEmitted: false,\n        bufferedRequestCount: 0,\n        corkedRequestsFree: [Object] },\n     writable: false,\n     allowHalfOpen: false,\n     _bytesDispatched: 236,\n     _sockname: null,\n     _pendingData: null,\n     _pendingEncoding: '',\n     server: null,\n     _server: null,\n     parser: null,\n     _httpMessage: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 5,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        upgrading: false,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedConnection: false,\n        _removedContLen: false,\n        _removedTE: false,\n        _contentLength: null,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Circular],\n        connection: [Circular],\n        _header: 'POST /devices/ HTTP/1.1\\r\\nContent-Type: application/x-www-form-urlencoded\\r\\nhost: localhost:3000\\r\\ncontent-length: 99\\r\\nConnection: close\\r\\n\\r\\n',\n        _onPendingData: [Function: noopPendingOutput],\n        agent: [Agent],\n        socketPath: undefined,\n        timeout: undefined,\n        method: 'POST',\n        path: '/devices/',\n        _ended: true,\n        res: [Circular],\n        aborted: undefined,\n        timeoutCb: null,\n        upgradeOrConnect: false,\n        parser: null,\n        maxHeadersCount: null,\n        [Symbol(outHeadersKey)]: [Object] },\n     read: [Function],\n     _consuming: true,\n     _idleNext: null,\n     _idlePrev: null,\n     _idleTimeout: -1,\n     [Symbol(asyncId)]: 1297,\n     [Symbol(bytesRead)]: 303 },\n  _consuming: true,\n  _dumped: false,\n  req: \n   ClientRequest {\n     domain: null,\n     _events: \n      { socket: [Function],\n        response: [Function: bound ],\n        error: [Function: bound ],\n        drain: [Function],\n        prefinish: [Function: requestOnPrefinish] },\n     _eventsCount: 5,\n     _maxListeners: undefined,\n     output: [],\n     outputEncodings: [],\n     outputCallbacks: [],\n     outputSize: 0,\n     writable: true,\n     _last: true,\n     upgrading: false,\n     chunkedEncoding: false,\n     shouldKeepAlive: false,\n     useChunkedEncodingByDefault: true,\n     sendDate: false,\n     _removedConnection: false,\n     _removedContLen: false,\n     _removedTE: false,\n     _contentLength: null,\n     _hasBody: true,\n     _trailer: '',\n     finished: true,\n     _headerSent: true,\n     socket: \n      Socket {\n        connecting: false,\n        _hadError: false,\n        _handle: null,\n        _parent: null,\n        _host: 'localhost',\n        _readableState: [ReadableState],\n        readable: false,\n        domain: null,\n        _events: [Object],\n        _eventsCount: 8,\n        _maxListeners: undefined,\n        _writableState: [WritableState],\n        writable: false,\n        allowHalfOpen: false,\n        _bytesDispatched: 236,\n        _sockname: null,\n        _pendingData: null,\n        _pendingEncoding: '',\n        server: null,\n        _server: null,\n        parser: null,\n        _httpMessage: [Circular],\n        read: [Function],\n        _consuming: true,\n        _idleNext: null,\n        _idlePrev: null,\n        _idleTimeout: -1,\n        [Symbol(asyncId)]: 1297,\n        [Symbol(bytesRead)]: 303 },\n     connection: \n      Socket {\n        connecting: false,\n        _hadError: false,\n        _handle: null,\n        _parent: null,\n        _host: 'localhost',\n        _readableState: [ReadableState],\n        readable: false,\n        domain: null,\n        _events: [Object],\n        _eventsCount: 8,\n        _maxListeners: undefined,\n        _writableState: [WritableState],\n        writable: false,\n        allowHalfOpen: false,\n        _bytesDispatched: 236,\n        _sockname: null,\n        _pendingData: null,\n        _pendingEncoding: '',\n        server: null,\n        _server: null,\n        parser: null,\n        _httpMessage: [Circular],\n        read: [Function],\n        _consuming: true,\n        _idleNext: null,\n        _idlePrev: null,\n        _idleTimeout: -1,\n        [Symbol(asyncId)]: 1297,\n        [Symbol(bytesRead)]: 303 },\n     _header: 'POST /devices/ HTTP/1.1\\r\\nContent-Type: application/x-www-form-urlencoded\\r\\nhost: localhost:3000\\r\\ncontent-length: 99\\r\\nConnection: close\\r\\n\\r\\n',\n     _onPendingData: [Function: noopPendingOutput],\n     agent: \n      Agent {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 1,\n        _maxListeners: undefined,\n        defaultPort: 80,\n        protocol: 'http:',\n        options: [Object],\n        requests: {},\n        sockets: [Object],\n        freeSockets: {},\n        keepAliveMsecs: 1000,\n        keepAlive: false,\n        maxSockets: Infinity,\n        maxFreeSockets: 256 },\n     socketPath: undefined,\n     timeout: undefined,\n     method: 'POST',\n     path: '/devices/',\n     _ended: true,\n     res: [Circular],\n     aborted: undefined,\n     timeoutCb: null,\n     upgradeOrConnect: false,\n     parser: null,\n     maxHeadersCount: null,\n     [Symbol(outHeadersKey)]: \n      { 'content-type': [Array],\n        host: [Array],\n        'content-length': [Array] } },\n  request: \n   Request {\n     domain: null,\n     _events: \n      { error: [Function: bound ],\n        complete: [Function: bound ],\n        pipe: [Function],\n        data: [Function],\n        end: [Function] },\n     _eventsCount: 5,\n     _maxListeners: undefined,\n     method: 'POST',\n     headers: \n      { 'Content-Type': 'application/x-www-form-urlencoded',\n        'content-length': 99 },\n     callback: [Function],\n     readable: true,\n     writable: true,\n     explicitMethod: true,\n     _qs: \n      Querystring {\n        request: [Circular],\n        lib: [Object],\n        useQuerystring: undefined,\n        parseOptions: {},\n        stringifyOptions: {} },\n     _auth: \n      Auth {\n        request: [Circular],\n        hasAuth: false,\n        sentAuth: false,\n        bearerToken: null,\n        user: null,\n        pass: null },\n     _oauth: OAuth { request: [Circular], params: null },\n     _multipart: \n      Multipart {\n        request: [Circular],\n        boundary: '9c5b6ec3-c2b7-450c-9082-c368a50e6ad0',\n        chunked: false,\n        body: null },\n     _redirect: \n      Redirect {\n        request: [Circular],\n        followRedirect: true,\n        followRedirects: true,\n        followAllRedirects: false,\n        followOriginalHttpMethod: false,\n        allowRedirect: [Function],\n        maxRedirects: 10,\n        redirects: [],\n        redirectsFollowed: 0,\n        removeRefererHeader: false },\n     _tunnel: \n      Tunnel {\n        request: [Circular],\n        proxyHeaderWhiteList: [Array],\n        proxyHeaderExclusiveList: [] },\n     setHeader: [Function],\n     hasHeader: [Function],\n     getHeader: [Function],\n     removeHeader: [Function],\n     localAddress: undefined,\n     pool: {},\n     dests: [],\n     __isRequestRequest: true,\n     _callback: [Function: onResponse],\n     uri: \n      Url {\n        protocol: 'http:',\n        slashes: true,\n        auth: null,\n        host: 'localhost:3000',\n        port: '3000',\n        hostname: 'localhost',\n        hash: null,\n        search: null,\n        query: null,\n        pathname: '/devices/',\n        path: '/devices/',\n        href: 'http://localhost:3000/devices/' },\n     proxy: null,\n     tunnel: false,\n     setHost: true,\n     originalCookieHeader: undefined,\n     _disableCookies: true,\n     _jar: undefined,\n     port: '3000',\n     host: 'localhost',\n     body: 'type=clone&uuid=5f82cb1d-a7f3-4234-879c-606c9a3047dc&token=22cca5be7d0af18d7da8299a31e366dcbcc49169',\n     path: '/devices/',\n     httpModule: \n      { _connectionListener: [Function: connectionListener],\n        METHODS: [Array],\n        STATUS_CODES: [Object],\n        Agent: [Function],\n        ClientRequest: [Function],\n        globalAgent: [Agent],\n        IncomingMessage: [Function],\n        OutgoingMessage: [Function],\n        Server: [Function],\n        ServerResponse: [Function],\n        createServer: [Function: createServer],\n        get: [Function: get],\n        request: [Function: request] },\n     agentClass: { [Function: Agent] super_: [Function], defaultMaxSockets: Infinity },\n     agent: \n      Agent {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 1,\n        _maxListeners: undefined,\n        defaultPort: 80,\n        protocol: 'http:',\n        options: [Object],\n        requests: {},\n        sockets: [Object],\n        freeSockets: {},\n        keepAliveMsecs: 1000,\n        keepAlive: false,\n        maxSockets: Infinity,\n        maxFreeSockets: 256 },\n     _started: true,\n     href: 'http://localhost:3000/devices/',\n     req: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 5,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        upgrading: false,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedConnection: false,\n        _removedContLen: false,\n        _removedTE: false,\n        _contentLength: null,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Socket],\n        connection: [Socket],\n        _header: 'POST /devices/ HTTP/1.1\\r\\nContent-Type: application/x-www-form-urlencoded\\r\\nhost: localhost:3000\\r\\ncontent-length: 99\\r\\nConnection: close\\r\\n\\r\\n',\n        _onPendingData: [Function: noopPendingOutput],\n        agent: [Agent],\n        socketPath: undefined,\n        timeout: undefined,\n        method: 'POST',\n        path: '/devices/',\n        _ended: true,\n        res: [Circular],\n        aborted: undefined,\n        timeoutCb: null,\n        upgradeOrConnect: false,\n        parser: null,\n        maxHeadersCount: null,\n        [Symbol(outHeadersKey)]: [Object] },\n     ntick: true,\n     response: [Circular],\n     originalHost: 'localhost:3000',\n     originalHostHeaderName: 'host',\n     responseContent: [Circular],\n     _destdata: true,\n     _ended: true,\n     _callbackCalled: true },\n  toJSON: [Function: responseToJSON],\n  caseless: \n   Caseless {\n     dict: \n      { 'x-powered-by': 'Express',\n        vary: 'Origin',\n        'access-control-allow-credentials': 'true',\n        'content-type': 'application/json; charset=utf-8',\n        'content-length': '23',\n        etag: 'W/\"17-T/rW1BQtPtOdPdiL8RI/XtHXZdY\"',\n        date: 'Sun, 01 Sep 2019 17:23:31 GMT',\n        connection: 'close' } },\n  read: [Function],\n  body: '\"Device not registered\"' }","level":"debug"}
[winston] Attempt to write logs with no transports {"message":"Unexpected error in POST /api/signup","level":"error"}
[winston] Attempt to write logs with no transports {"message":"Body: { email: 'rhpr@cesar.org.br', password: '123qwe!@#QWE' }","level":"debug"}
[winston] Attempt to write logs with no transports {"message":"Headers: { host: 'knot.local',\n  connection: 'keep-alive',\n  'content-length': '55',\n  accept: 'application/json, text/plain, */*',\n  origin: 'http://knot.local',\n  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36',\n  'content-type': 'application/json;charset=UTF-8',\n  referer: 'http://knot.local/',\n  'accept-encoding': 'gzip, deflate',\n  'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7',\n  cookie: 'm=' }","level":"debug"}
[winston] Attempt to write logs with no transports {"message":"{ Error\n    at new FogServiceError (/usr/local/bin/knot-web-KNOT-v02.00/app/services/fog.js:25:17)\n    at parseResponseError (/usr/local/bin/knot-web-KNOT-v02.00/app/services/fog.js:45:10)\n    at Request.onResponse [as _callback] (/usr/local/bin/knot-web-KNOT-v02.00/app/services/fog.js:167:16)\n    at Request.self.callback (/usr/local/bin/knot-web-KNOT-v02.00/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:160:13)\n    at Request.<anonymous> (/usr/local/bin/knot-web-KNOT-v02.00/node_modules/request/request.js:1157:10)\n    at Request.emit (events.js:160:13)\n    at IncomingMessage.<anonymous> (/usr/local/bin/knot-web-KNOT-v02.00/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:255:19)\n    at IncomingMessage.emit (events.js:165:20)\n    at endReadableNT (_stream_readable.js:1101:12)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'FogServiceError',\n  message: 'Unknown error',\n  stack: 'Error\\n    at new FogServiceError (/usr/local/bin/knot-web-KNOT-v02.00/app/services/fog.js:25:17)\\n    at parseResponseError (/usr/local/bin/knot-web-KNOT-v02.00/app/services/fog.js:45:10)\\n    at Request.onResponse [as _callback] (/usr/local/bin/knot-web-KNOT-v02.00/app/services/fog.js:167:16)\\n    at Request.self.callback (/usr/local/bin/knot-web-KNOT-v02.00/node_modules/request/request.js:185:22)\\n    at Request.emit (events.js:160:13)\\n    at Request.<anonymous> (/usr/local/bin/knot-web-KNOT-v02.00/node_modules/request/request.js:1157:10)\\n    at Request.emit (events.js:160:13)\\n    at IncomingMessage.<anonymous> (/usr/local/bin/knot-web-KNOT-v02.00/node_modules/request/request.js:1079:12)\\n    at Object.onceWrapper (events.js:255:19)\\n    at IncomingMessage.emit (events.js:165:20)\\n    at endReadableNT (_stream_readable.js:1101:12)\\n    at process._tickCallback (internal/process/next_tick.js:152:19)' }","level":"debug"}
```

We could do a workaround by accessing the gateway via ssh and restarting the knot-fog process:
```
/etc/knot/stop.sh knot-fog
/etc/knot/start.sh knot-fog
```

@joaoaneto and @alla3 can you verify that?

**Comment by ramonhpr** [comment]
Since we removed the fog from gateway this issue can be closed
