### ISSUE TITLE
Trouble to run (npm start)

### ISSUE THREAD

**Issue by gabsprates** [CESARBR/knot-gateway-webui#5]
Hi,

What I need to run this?

After `npm install`, when I run, it returns this:

```
$ knot-gateway-webui/ > npm start

> gateway@1.0.0 start /home/tests/knot-gateway-webui
> CONFIG_FILE=./app/config/gatewayConfig.json KEYS_FILE=./app/config/keys.json node server.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tests/knot-gateway-webui/app/routes/signup.js:6:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tests/knot-gateway-webui/app/routes/api.js:10:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! gateway@1.0.0 start: `CONFIG_FILE=./app/config/gatewayConfig.json KEYS_FILE=./app/config/keys.json node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gateway@1.0.0 start script 'CONFIG_FILE=./app/config/gatewayConfig.json KEYS_FILE=./app/config/keys.json node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gateway package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     CONFIG_FILE=./app/config/gatewayConfig.json KEYS_FILE=./app/config/keys.json node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gateway
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gateway
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tests/knot-gateway-webui/npm-debug.log
```

I'm using `node v7.5.0` and `npm  v4.1.2`, and the `./app/config/gatewayConfig.json` have the same content that this repo.

**Comment by figueredo** [comment]
Hi @gabsprates, I think the `request` module was missing from the `package.json`, we made a couple of fixes and updated the build and run instructions. Please take a look at the README and let us know if you have any issues running it.
